name: macOS

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Homebrew packages
      run: |
        export HOMEBREW_NO_INSTALL_CLEANUP=1
        export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
        # Skip brew update for now, see https://github.com/actions/setup-python/issues/577
        # brew update
        brew install ffmpeg xxhash llvm meson vapoursynth

    - name: Set environment variables for Clang/LLVM
      run: |
        echo "CC=/usr/local/opt/llvm/bin/clang" >> $GITHUB_ENV
        echo "CXX=/usr/local/opt/llvm/bin/clang++" >> $GITHUB_ENV
        echo "PATH=/usr/local/opt/llvm/bin:$PATH" >> $GITHUB_ENV

    - name: Build
      run: |
        meson setup -Dcpp_link_args=-fuse-ld=lld build
        ninja -C build
